name: CI

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - '*'

concurrency:
  group: 'ci-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  lint:
    name: Lint and Format
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
      - name: Setup Bun environment
        uses: oven-sh/setup-bun@v2.0.1
        with:
          bun-version: 1.2.10
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Verify Format
        run: |
          bun run format:check
      - name: Run Lint
        run: |
          bun run lint:ci

  build:
    name: Build
    timeout-minutes: 5
    needs: [lint]
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
      - name: Setup Bun environment
        uses: oven-sh/setup-bun@v2.0.1
        with:
          bun-version: 1.2.10
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run Build
        run: bun run build
